
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    EMAIL VARCHAR(150) UNIQUE,
    CLAVE_ACCESO VARCHAR(255),
    UBICACION VARCHAR(100),
    TELEFONO VARCHAR(20),
    FECHA_REGISTRO TIMESTAMP
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY,
    NOMBRE VARCHAR(100) UNIQUE
);

CREATE TABLE PROYECTO (
    ID_PROYECTO INT PRIMARY KEY,
    CLIENTE_ID INT,
    TITULO VARCHAR(150),
    DESCRIPCION TEXT,
    PRESUPUESTO DECIMAL(12,2),
    ESTADO VARCHAR(20),
    FECHA_PUBLICACION TIMESTAMP,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PROYECTO_CATEGORIA (
    PROYECTO_ID INT,
    CATEGORIA_ID INT,
    PRIMARY KEY (PROYECTO_ID, CATEGORIA_ID),
    FOREIGN KEY (PROYECTO_ID) REFERENCES PROYECTO(ID_PROYECTO),
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID_CATEGORIA)
);
